INSERT INTO estado VALUES (22 , 'Querétaro');
INSERT INTO estado VALUES (23 , 'Quintana Roo');
INSERT INTO estado VALUES (24 , 'San Luis Potosí');
INSERT INTO estado VALUES (02 , 'Baja California');
INSERT INTO estado VALUES (25 , 'Sinaloa');
INSERT INTO estado VALUES (26 , 'Sonora');
INSERT INTO estado VALUES (04 , 'Campeche');
INSERT INTO estado VALUES (05 , 'Coahuila de Zaragoza');
INSERT INTO estado VALUES (27 , 'Tabasco');
INSERT INTO estado VALUES (06 , 'Colima');
INSERT INTO estado VALUES (29 , 'Tlaxcala');
INSERT INTO estado VALUES (07 , 'Chiapas');
INSERT INTO estado VALUES (08 , 'Chihuahua');
INSERT INTO estado VALUES (09 , 'Distrito Federal');
INSERT INTO estado VALUES (30 , 'Veracruz de Ignacio de la Llave');
INSERT INTO estado VALUES (31 , 'Yucatán');
INSERT INTO estado VALUES (10 , 'Durango');
INSERT INTO estado VALUES (32 , 'Zacatecas');
INSERT INTO estado VALUES (11 , 'Guanajuato');
INSERT INTO estado VALUES (12 , 'Guerrero');
INSERT INTO estado VALUES (13 , 'Hidalgo');
INSERT INTO estado VALUES (14 , 'Jalisco');
INSERT INTO estado VALUES (15 , 'México');
INSERT INTO estado VALUES (16 , 'Michoacón de Ocampo');
INSERT INTO estado VALUES (17 , 'Morelos');
INSERT INTO estado VALUES (18 , 'Nayarit');
INSERT INTO estado VALUES (20 , 'Oaxaca');
INSERT INTO estado VALUES (21 , 'Puebla');

