INSERT INTO estado VALUES (22 , 'Querétaro');
INSERT INTO estado VALUES (23 , 'Quintana Roo');
INSERT INTO estado VALUES (24 , 'San Luis Potosí');
INSERT INTO estado VALUES (02 , 'Baja California');
INSERT INTO estado VALUES (25 , 'Sinaloa');
INSERT INTO estado VALUES (26 , 'Sonora');
INSERT INTO estado VALUES (04 , 'Campeche');
INSERT INTO estado VALUES (05 , 'Coahuila de Zaragoza');
INSERT INTO estado VALUES (27 , 'Tabasco');
INSERT INTO estado VALUES (06 , 'Colima');
INSERT INTO estado VALUES (29 , 'Tlaxcala');
INSERT INTO estado VALUES (07 , 'Chiapas');
INSERT INTO estado VALUES (08 , 'Chihuahua');
INSERT INTO estado VALUES (09 , 'Distrito Federal');
INSERT INTO estado VALUES (30 , 'Veracruz de Ignacio de la Llave');
INSERT INTO estado VALUES (31 , 'Yucatán');
INSERT INTO estado VALUES (10 , 'Durango');
INSERT INTO estado VALUES (32 , 'Zacatecas');
INSERT INTO estado VALUES (11 , 'Guanajuato');
INSERT INTO estado VALUES (12 , 'Guerrero');
INSERT INTO estado VALUES (13 , 'Hidalgo');
INSERT INTO estado VALUES (14 , 'Jalisco');
INSERT INTO estado VALUES (15 , 'México');
INSERT INTO estado VALUES (16 , 'Michoacón de Ocampo');
INSERT INTO estado VALUES (17 , 'Morelos');
INSERT INTO estado VALUES (18 , 'Nayarit');
INSERT INTO estado VALUES (20 , 'Oaxaca');
INSERT INTO estado VALUES (21 , 'Puebla');

INSERT INTO municipio VALUES (500 , 'Santiago Yosondúa', 20);
INSERT INTO municipio VALUES (501 , 'Santiago Yucuyachi', 20);
INSERT INTO municipio VALUES (502 , 'Santiago Zacatepec', 20);
INSERT INTO municipio VALUES (503 , 'Santiago Zoochila', 20);
INSERT INTO municipio VALUES (504 , 'Nuevo Zoquiápam', 20);
INSERT INTO municipio VALUES (505 , 'Santo Domingo Ingenio', 20);
INSERT INTO municipio VALUES (506 , 'Santo Domingo Albarradas', 20);
INSERT INTO municipio VALUES (508 , 'Santo Domingo Chihuitán', 20);
INSERT INTO municipio VALUES (509 , 'Santo Domingo de Morelos', 20);
INSERT INTO municipio VALUES (510 , 'Santo Domingo Ixcatlán', 20);
INSERT INTO municipio VALUES (511 , 'Santo Domingo Nuxaá', 20);
INSERT INTO municipio VALUES (512 , 'Santo Domingo Ozolotepec', 20);
INSERT INTO municipio VALUES (513 , 'Santo Domingo Petapa', 20);
INSERT INTO municipio VALUES (514 , 'Santo Domingo Roayaga', 20);
INSERT INTO municipio VALUES (515 , 'Santo Domingo Tehuantepec', 20);
INSERT INTO municipio VALUES (517 , 'Santo Domingo Tepuxtepec', 20);
INSERT INTO municipio VALUES (520 , 'Santo Domingo Tonalá', 20);
INSERT INTO municipio VALUES (521 , 'Santo Domingo Tonaltepec', 20);
INSERT INTO municipio VALUES (401 , 'Santa María Colotepec', 20);
INSERT INTO municipio VALUES (523 , 'Santo Domingo Yanhuitlán', 20);
INSERT INTO municipio VALUES (403 , 'Santa María Coyotepec', 20);
INSERT INTO municipio VALUES (525 , 'Santo Domingo Zanatepec', 20);
INSERT INTO municipio VALUES (404 , 'Santa María Chachoápam', 20);
INSERT INTO municipio VALUES (526 , 'Santos Reyes Nopala', 20);
INSERT INTO municipio VALUES (405 , 'Villa de Chilapa de Díaz', 20);
INSERT INTO municipio VALUES (406 , 'Santa María Chilchotla', 20);
INSERT INTO municipio VALUES (527 , 'Santos Reyes Pápalo', 20);
INSERT INTO municipio VALUES (407 , 'Santa María Chimalapa', 20);
INSERT INTO municipio VALUES (528 , 'Santos Reyes Tepejillo', 20);
INSERT INTO municipio VALUES (529 , 'Santos Reyes Yucuná', 20);
INSERT INTO municipio VALUES (409 , 'Santa María del Tule', 20);
INSERT INTO municipio VALUES (530 , 'Santo Tomás Jalieza', 20);
INSERT INTO municipio VALUES (531 , 'Santo Tomás Mazaltepec', 20);
INSERT INTO municipio VALUES (410 , 'Santa María Ecatepec', 20);
INSERT INTO municipio VALUES (411 , 'Santa María Guelacé', 20);
INSERT INTO municipio VALUES (532 , 'Santo Tomás Ocotepec', 20);
INSERT INTO municipio VALUES (533 , 'Santo Tomás Tamazulapan', 20);
INSERT INTO municipio VALUES (412 , 'Santa María Guienagati', 20);
INSERT INTO municipio VALUES (534 , 'San Vicente Coatlán', 20);
INSERT INTO municipio VALUES (413 , 'Santa María Huatulco', 20);
INSERT INTO municipio VALUES (535 , 'San Vicente Lachixío', 20);
INSERT INTO municipio VALUES (414 , 'Santa María Huazolotitlán', 20);
INSERT INTO municipio VALUES (415 , 'Santa María Ipalapa', 20);
INSERT INTO municipio VALUES (416 , 'Santa María Ixcatlán', 20);
INSERT INTO municipio VALUES (537 , 'Silacayoápam', 20);
INSERT INTO municipio VALUES (417 , 'Santa María Jacatepec', 20);
INSERT INTO municipio VALUES (418 , 'Santa María Jalapa del Marqués', 20);
INSERT INTO municipio VALUES (419 , 'Santa María Jaltianguis', 20);
INSERT INTO municipio VALUES (540 , 'Villa de Tamazulápam del Progreso', 20);
INSERT INTO municipio VALUES (420 , 'Santa María Lachixío', 20);
INSERT INTO municipio VALUES (541 , 'Tanetze de Zaragoza', 20);
INSERT INTO municipio VALUES (421 , 'Santa María Mixtequilla', 20);
INSERT INTO municipio VALUES (300 , 'San Pedro Amuzgos', 20);
INSERT INTO municipio VALUES (422 , 'Santa María Nativitas', 20);
INSERT INTO municipio VALUES (301 , 'San Pedro Apóstol', 20);
INSERT INTO municipio VALUES (543 , 'Tataltepec de Valdés', 20);
INSERT INTO municipio VALUES (544 , 'Teococuilco de Marcos Pérez', 20);
INSERT INTO municipio VALUES (302 , 'San Pedro Atoyac', 20);
INSERT INTO municipio VALUES (545 , 'Teotitlán de Flores Magón', 20);
INSERT INTO municipio VALUES (303 , 'San Pedro Cajonos', 20);
INSERT INTO municipio VALUES (424 , 'Santa María Ozolotepec', 20);
INSERT INTO municipio VALUES (546 , 'Teotitlán del Valle', 20);
INSERT INTO municipio VALUES (304 , 'San Pedro Coxcaltepec Cántaros', 20);
INSERT INTO municipio VALUES (425 , 'Santa María Pápalo', 20);
INSERT INTO municipio VALUES (547 , 'Teotongo', 20);
INSERT INTO municipio VALUES (305 , 'San Pedro Comitancillo', 20);
INSERT INTO municipio VALUES (426 , 'Santa María Peñoles', 20);
INSERT INTO municipio VALUES (548 , 'Tepelmeme Villa de Morelos', 20);
INSERT INTO municipio VALUES (306 , 'San Pedro el Alto', 20);
INSERT INTO municipio VALUES (427 , 'Santa María Petapa', 20);
INSERT INTO municipio VALUES (428 , 'Santa María Quiegolani', 20);
INSERT INTO municipio VALUES (549 , 'Tezoatlán de Segura y Luna', 20);
INSERT INTO municipio VALUES (307 , 'San Pedro Huamelula', 20);
INSERT INTO municipio VALUES (308 , 'San Pedro Huilotepec', 20);
INSERT INTO municipio VALUES (309 , 'San Pedro Ixcatlán', 20);
INSERT INTO municipio VALUES (550 , 'San Jerónimo Tlacochahuaya', 20);
INSERT INTO municipio VALUES (551 , 'Tlacolula de Matamoros', 20);
INSERT INTO municipio VALUES (431 , 'Santa María Tecomavaca', 20);
INSERT INTO municipio VALUES (552 , 'Tlacotepec Plumas', 20);
INSERT INTO municipio VALUES (310 , 'San Pedro Ixtlahuaca', 20);
INSERT INTO municipio VALUES (432 , 'Santa María Temaxcalapa', 20);
INSERT INTO municipio VALUES (553 , 'Tlalixtac de Cabrera', 20);
INSERT INTO municipio VALUES (311 , 'San Pedro Jaltepetongo', 20);
INSERT INTO municipio VALUES (433 , 'Santa María Temaxcaltepec', 20);
INSERT INTO municipio VALUES (312 , 'San Pedro Jicayán', 20);
INSERT INTO municipio VALUES (554 , 'Totontepec Villa de Morelos', 20);
INSERT INTO municipio VALUES (434 , 'Santa María Teopoxco', 20);
INSERT INTO municipio VALUES (313 , 'San Pedro Jocotipac', 20);
INSERT INTO municipio VALUES (314 , 'San Pedro Juchatengo', 20);
INSERT INTO municipio VALUES (435 , 'Santa María Tepantlali', 20);
INSERT INTO municipio VALUES (315 , 'San Pedro Mártir', 20);
INSERT INTO municipio VALUES (557 , 'Unión Hidalgo', 20);
INSERT INTO municipio VALUES (436 , 'Santa María Texcatitlán', 20);
INSERT INTO municipio VALUES (316 , 'San Pedro Mártir Quiechapa', 20);
INSERT INTO municipio VALUES (558 , 'Valerio Trujano', 20);
INSERT INTO municipio VALUES (437 , 'Santa María Tlahuitoltepec', 20);
INSERT INTO municipio VALUES (559 , 'San Juan Bautista Valle Nacional', 20);
INSERT INTO municipio VALUES (438 , 'Santa María Tlalixtac', 20);
INSERT INTO municipio VALUES (439 , 'Santa María Tonameca', 20);
INSERT INTO municipio VALUES (318 , 'San Pedro Mixtepec -Dto. 22 -', 20);
INSERT INTO municipio VALUES (319 , 'San Pedro Mixtepec -Dto. 26 -', 20);
INSERT INTO municipio VALUES (560 , 'Villa Díaz Ordaz', 20);
INSERT INTO municipio VALUES (440 , 'Santa María Totolapilla', 20);
INSERT INTO municipio VALUES (441 , 'Santa María Xadani', 20);
INSERT INTO municipio VALUES (320 , 'San Pedro Molinos', 20);
INSERT INTO municipio VALUES (442 , 'Santa María Yalina', 20);
INSERT INTO municipio VALUES (200 , 'San Juan Juquila Mixes', 20);
INSERT INTO municipio VALUES (322 , 'San Pedro Ocopetatillo', 20);
INSERT INTO municipio VALUES (443 , 'Santa María Yavesía', 20);
INSERT INTO municipio VALUES (564 , 'Yutanduchi de Guerrero', 20);
INSERT INTO municipio VALUES (565 , 'Villa de Zaachila', 20);
INSERT INTO municipio VALUES (202 , 'San Juan Lachao', 20);
INSERT INTO municipio VALUES (444 , 'Santa María Yolotepec', 20);
INSERT INTO municipio VALUES (323 , 'San Pedro Ocotepec', 20);
INSERT INTO municipio VALUES (324 , 'San Pedro Pochutla', 20);
INSERT INTO municipio VALUES (445 , 'Santa María Yosoyúa', 20);
INSERT INTO municipio VALUES (325 , 'San Pedro Quiatoni', 20);
INSERT INTO municipio VALUES (446 , 'Santa María Yucuhiti', 20);
INSERT INTO municipio VALUES (205 , 'San Juan Lalana', 20);
INSERT INTO municipio VALUES (326 , 'San Pedro Sochiápam', 20);
INSERT INTO municipio VALUES (447 , 'Santa María Zacatepec', 20);
INSERT INTO municipio VALUES (568 , 'Zapotitlán Palmas', 20);
INSERT INTO municipio VALUES (206 , 'San Juan de los Cués', 20);
INSERT INTO municipio VALUES (448 , 'Santa María Zaniza', 20);
INSERT INTO municipio VALUES (327 , 'San Pedro Tapanatepec', 20);
INSERT INTO municipio VALUES (569 , 'Santa Inés de Zaragoza', 20);
INSERT INTO municipio VALUES (207 , 'San Juan Mazatlán', 20);
INSERT INTO municipio VALUES (208 , 'San Juan Mixtepec -Dto. 08 -', 20);
INSERT INTO municipio VALUES (209 , 'San Juan Mixtepec -Dto. 26 -', 20);
INSERT INTO municipio VALUES (570 , 'Zimatlán de Álvarez', 20);
INSERT INTO municipio VALUES (450 , 'Santiago Amoltepec', 20);
INSERT INTO municipio VALUES (330 , 'San Pedro Teutila', 20);
INSERT INTO municipio VALUES (451 , 'Santiago Apoala', 20);
INSERT INTO municipio VALUES (452 , 'Santiago Apóstol', 20);
INSERT INTO municipio VALUES (210 , 'San Juan Ñumí', 20);
INSERT INTO municipio VALUES (331 , 'San Pedro Tidaá', 20);
INSERT INTO municipio VALUES (211 , 'San Juan Ozolotepec', 20);
INSERT INTO municipio VALUES (453 , 'Santiago Astata', 20);
INSERT INTO municipio VALUES (212 , 'San Juan Petlapa', 20);
INSERT INTO municipio VALUES (333 , 'San Pedro Totolápam', 20);
INSERT INTO municipio VALUES (454 , 'Santiago Atitlán', 20);
INSERT INTO municipio VALUES (334 , 'Villa de Tututepec de Melchor Ocampo', 20);
INSERT INTO municipio VALUES (213 , 'San Juan Quiahije', 20);
INSERT INTO municipio VALUES (214 , 'San Juan Quiotepec', 20);
INSERT INTO municipio VALUES (335 , 'San Pedro Yaneri', 20);
INSERT INTO municipio VALUES (456 , 'Santiago Cacaloxtepec', 20);
INSERT INTO municipio VALUES (336 , 'San Pedro Yólox', 20);
INSERT INTO municipio VALUES (457 , 'Santiago Camotlán', 20);
INSERT INTO municipio VALUES (458 , 'Santiago Comaltepec', 20);
INSERT INTO municipio VALUES (216 , 'San Juan Tabaá', 20);
INSERT INTO municipio VALUES (337 , 'San Pedro y San Pablo Ayutla', 20);
INSERT INTO municipio VALUES (338 , 'Villa de Etla', 20);
INSERT INTO municipio VALUES (217 , 'San Juan Tamazola', 20);
INSERT INTO municipio VALUES (459 , 'Santiago Chazumba', 20);
INSERT INTO municipio VALUES (339 , 'San Pedro y San Pablo Teposcolula', 20);
INSERT INTO municipio VALUES (218 , 'San Juan Teita', 20);
INSERT INTO municipio VALUES (219 , 'San Juan Teitipac', 20);
INSERT INTO municipio VALUES (460 , 'Santiago Choápam', 20);
INSERT INTO municipio VALUES (461 , 'Santiago del Río', 20);
INSERT INTO municipio VALUES (340 , 'San Pedro y San Pablo Tequixtepec', 20);
INSERT INTO municipio VALUES (220 , 'San Juan Tepeuxila', 20);
INSERT INTO municipio VALUES (100 , 'San Andrés Yaá', 20);
INSERT INTO municipio VALUES (342 , 'San Raymundo Jalpan', 20);
INSERT INTO municipio VALUES (464 , 'Santiago Ihuitlán Plumas', 20);
INSERT INTO municipio VALUES (222 , 'San Juan Yaeé', 20);
INSERT INTO municipio VALUES (343 , 'San Sebastián Abasolo', 20);
INSERT INTO municipio VALUES (223 , 'San Juan Yatzona', 20);
INSERT INTO municipio VALUES (102 , 'San Andrés Zautla', 20);
INSERT INTO municipio VALUES (103 , 'San Antonino Castillo Velasco', 20);
INSERT INTO municipio VALUES (466 , 'Santiago Ixtayutla', 20);
INSERT INTO municipio VALUES (345 , 'San Sebastián Ixcapa', 20);
INSERT INTO municipio VALUES (104 , 'San Antonino el Alto', 20);
INSERT INTO municipio VALUES (225 , 'San Lorenzo', 20);
INSERT INTO municipio VALUES (467 , 'Santiago Jamiltepec', 20);
INSERT INTO municipio VALUES (346 , 'San Sebastián Nicananduta', 20);
INSERT INTO municipio VALUES (468 , 'Santiago Jocotepec', 20);
INSERT INTO municipio VALUES (347 , 'San Sebastián Río Hondo', 20);
INSERT INTO municipio VALUES (226 , 'San Lorenzo Albarradas', 20);
INSERT INTO municipio VALUES (105 , 'San Antonino Monte Verde', 20);
INSERT INTO municipio VALUES (469 , 'Santiago Juxtlahuaca', 20);
INSERT INTO municipio VALUES (348 , 'San Sebastián Tecomaxtlahuaca', 20);
INSERT INTO municipio VALUES (228 , 'San Lorenzo Cuaunecuiltitla', 20);
INSERT INTO municipio VALUES (107 , 'San Antonio de la Cal', 20);
INSERT INTO municipio VALUES (349 , 'San Sebastián Teitipac', 20);
INSERT INTO municipio VALUES (229 , 'San Lorenzo Texmelúcan', 20);
INSERT INTO municipio VALUES (108 , 'San Antonio Huitepec', 20);
INSERT INTO municipio VALUES (470 , 'Santiago Lachiguiri', 20);
INSERT INTO municipio VALUES (471 , 'Santiago Lalopa', 20);
INSERT INTO municipio VALUES (350 , 'San Sebastián Tutla', 20);
INSERT INTO municipio VALUES (472 , 'Santiago Laollaga', 20);
INSERT INTO municipio VALUES (473 , 'Santiago Laxopa', 20);
INSERT INTO municipio VALUES (110 , 'San Antonio Sinicahua', 20);
INSERT INTO municipio VALUES (352 , 'San Simón Zahuatlán', 20);
INSERT INTO municipio VALUES (231 , 'San Lucas Camotlán', 20);
INSERT INTO municipio VALUES (232 , 'San Lucas Ojitlán', 20);
INSERT INTO municipio VALUES (111 , 'San Antonio Tepetlapa', 20);
INSERT INTO municipio VALUES (354 , 'Santa Ana Ateixtlahuaca', 20);
INSERT INTO municipio VALUES (233 , 'San Lucas Quiaviní', 20);
INSERT INTO municipio VALUES (475 , 'Santiago Matatlán', 20);
INSERT INTO municipio VALUES (112 , 'San Baltazar Chichicápam', 20);
INSERT INTO municipio VALUES (234 , 'San Lucas Zoquiápam', 20);
INSERT INTO municipio VALUES (113 , 'San Baltazar Loxicha', 20);
INSERT INTO municipio VALUES (355 , 'Santa Ana Cuauhtémoc', 20);
INSERT INTO municipio VALUES (114 , 'San Baltazar Yatzachi el Bajo', 20);
INSERT INTO municipio VALUES (235 , 'San Luis Amatlán', 20);
INSERT INTO municipio VALUES (356 , 'Santa Ana del Valle', 20);
INSERT INTO municipio VALUES (236 , 'San Marcial Ozolotepec', 20);
INSERT INTO municipio VALUES (115 , 'San Bartolo Coyotepec', 20);
INSERT INTO municipio VALUES (116 , 'San Bartolomé Ayautla', 20);
INSERT INTO municipio VALUES (359 , 'Santa Ana Yareni', 20);
INSERT INTO municipio VALUES (117 , 'San Bartolomé Loxicha', 20);
INSERT INTO municipio VALUES (238 , 'San Martín de los Cansecos', 20);
INSERT INTO municipio VALUES (118 , 'San Bartolomé Quialana', 20);
INSERT INTO municipio VALUES (119 , 'San Bartolomé Yucuañe', 20);
INSERT INTO municipio VALUES (480 , 'Santiago Nundiche', 20);
INSERT INTO municipio VALUES (360 , 'Santa Ana Zegache', 20);
INSERT INTO municipio VALUES (481 , 'Santiago Nuyoó', 20);
INSERT INTO municipio VALUES (361 , 'Santa Catalina Quierí', 20);
INSERT INTO municipio VALUES (240 , 'San Martín Itunyoso', 20);
INSERT INTO municipio VALUES (482 , 'Santiago Pinotepa Nacional', 20);
INSERT INTO municipio VALUES (120 , 'San Bartolomé Zoogocho', 20);
INSERT INTO municipio VALUES (362 , 'Santa Catarina Cuixtla', 20);
INSERT INTO municipio VALUES (363 , 'Santa Catarina Ixtepeji', 20);
INSERT INTO municipio VALUES (242 , 'San Martín Peras', 20);
INSERT INTO municipio VALUES (484 , 'Santiago Tamazola', 20);
INSERT INTO municipio VALUES (121 , 'San Bartolo Soyaltepec', 20);
INSERT INTO municipio VALUES (001 , 'Abejones', 20);
INSERT INTO municipio VALUES (122 , 'San Bartolo Yautepec', 20);
INSERT INTO municipio VALUES (243 , 'San Martín Tilcajete', 20);
INSERT INTO municipio VALUES (364 , 'Santa Catarina Juquila', 20);
INSERT INTO municipio VALUES (485 , 'Santiago Tapextla', 20);
INSERT INTO municipio VALUES (244 , 'San Martín Toxpalan', 20);
INSERT INTO municipio VALUES (002 , 'Acatlán de Pérez Figueroa', 20);
INSERT INTO municipio VALUES (365 , 'Santa Catarina Lachatao', 20);
INSERT INTO municipio VALUES (123 , 'San Bernardo Mixtepec', 20);
INSERT INTO municipio VALUES (486 , 'Villa Tejúpam de la Unión', 20);
INSERT INTO municipio VALUES (124 , 'San Blas Atempa', 20);
INSERT INTO municipio VALUES (003 , 'Asunción Cacalotepec', 20);
INSERT INTO municipio VALUES (488 , 'Santiago Tepetlapa', 20);
INSERT INTO municipio VALUES (246 , 'San Mateo Cajonos', 20);
INSERT INTO municipio VALUES (125 , 'San Carlos Yautepec', 20);
INSERT INTO municipio VALUES (367 , 'Santa Catarina Mechoacán', 20);
INSERT INTO municipio VALUES (247 , 'Capulálpam de Méndez', 20);
INSERT INTO municipio VALUES (126 , 'San Cristóbal Amatlán', 20);
INSERT INTO municipio VALUES (368 , 'Santa Catarina Minas', 20);
INSERT INTO municipio VALUES (005 , 'Asunción Ixtaltepec', 20);
INSERT INTO municipio VALUES (489 , 'Santiago Tetepec', 20);
INSERT INTO municipio VALUES (127 , 'San Cristóbal Amoltepec', 20);
INSERT INTO municipio VALUES (006 , 'Asunción Nochixtlán', 20);
INSERT INTO municipio VALUES (248 , 'San Mateo del Mar', 20);
INSERT INTO municipio VALUES (249 , 'San Mateo Yoloxochitlán', 20);
INSERT INTO municipio VALUES (128 , 'San Cristóbal Lachirioag', 20);
INSERT INTO municipio VALUES (007 , 'Asunción Ocotlán', 20);
INSERT INTO municipio VALUES (129 , 'San Cristóbal Suchixtlahuaca', 20);
INSERT INTO municipio VALUES (008 , 'Asunción Tlacolulita', 20);
INSERT INTO municipio VALUES (009 , 'Ayotzintepec', 20);
INSERT INTO municipio VALUES (490 , 'Santiago Texcalcingo', 20);
INSERT INTO municipio VALUES (491 , 'Santiago Textitlán', 20);
INSERT INTO municipio VALUES (370 , 'Santa Catarina Tayata', 20);
INSERT INTO municipio VALUES (371 , 'Santa Catarina Ticuá', 20);
INSERT INTO municipio VALUES (492 , 'Santiago Tilantongo', 20);
INSERT INTO municipio VALUES (372 , 'Santa Catarina Yosonotú', 20);
INSERT INTO municipio VALUES (251 , 'San Mateo Nejápam', 20);
INSERT INTO municipio VALUES (130 , 'San Dionisio del Mar', 20);
INSERT INTO municipio VALUES (131 , 'San Dionisio Ocotepec', 20);
INSERT INTO municipio VALUES (252 , 'San Mateo Peñasco', 20);
INSERT INTO municipio VALUES (494 , 'Santiago Tlazoyaltepec', 20);
INSERT INTO municipio VALUES (374 , 'Santa Cruz Acatepec', 20);
INSERT INTO municipio VALUES (253 , 'San Mateo Piñas', 20);
INSERT INTO municipio VALUES (495 , 'Santiago Xanica', 20);
INSERT INTO municipio VALUES (011 , 'Calihualá', 20);
INSERT INTO municipio VALUES (496 , 'Santiago Xiacuí', 20);
INSERT INTO municipio VALUES (012 , 'Candelaria Loxicha', 20);
INSERT INTO municipio VALUES (133 , 'San Esteban Atatlahuca', 20);
INSERT INTO municipio VALUES (134 , 'San Felipe Jalapa de Díaz', 20);
INSERT INTO municipio VALUES (497 , 'Santiago Yaitepec', 20);
INSERT INTO municipio VALUES (498 , 'Santiago Yaveo', 20);
INSERT INTO municipio VALUES (256 , 'San Mateo Tlapiltepec', 20);
INSERT INTO municipio VALUES (135 , 'San Felipe Tejalápam', 20);
INSERT INTO municipio VALUES (014 , 'Ciudad Ixtepec', 20);
INSERT INTO municipio VALUES (377 , 'Santa Cruz Itundujia', 20);
INSERT INTO municipio VALUES (136 , 'San Felipe Usila', 20);
INSERT INTO municipio VALUES (378 , 'Santa Cruz Mixtepec', 20);
INSERT INTO municipio VALUES (257 , 'San Melchor Betaza', 20);
INSERT INTO municipio VALUES (015 , 'Coatecas Altas', 20);
INSERT INTO municipio VALUES (499 , 'Santiago Yolomécatl', 20);
INSERT INTO municipio VALUES (258 , 'San Miguel Achiutla', 20);
INSERT INTO municipio VALUES (379 , 'Santa Cruz Nundaco', 20);
INSERT INTO municipio VALUES (016 , 'Coicoyán de las Flores', 20);
INSERT INTO municipio VALUES (138 , 'San Francisco Cajonos', 20);
INSERT INTO municipio VALUES (259 , 'San Miguel Ahuehuetitlán', 20);
INSERT INTO municipio VALUES (018 , 'Concepción Buenavista', 20);
INSERT INTO municipio VALUES (139 , 'San Francisco Chapulapa', 20);
INSERT INTO municipio VALUES (019 , 'Concepción Pápalo', 20);
INSERT INTO municipio VALUES (380 , 'Santa Cruz Papalutla', 20);
INSERT INTO municipio VALUES (260 , 'San Miguel Aloápam', 20);
INSERT INTO municipio VALUES (261 , 'San Miguel Amatitlán', 20);
INSERT INTO municipio VALUES (382 , 'Santa Cruz Tacahua', 20);
INSERT INTO municipio VALUES (262 , 'San Miguel Amatlán', 20);
INSERT INTO municipio VALUES (141 , 'San Francisco del Mar', 20);
INSERT INTO municipio VALUES (020 , 'Constancia del Rosario', 20);
INSERT INTO municipio VALUES (142 , 'San Francisco Huehuetlán', 20);
INSERT INTO municipio VALUES (263 , 'San Miguel Coatlán', 20);
INSERT INTO municipio VALUES (384 , 'Santa Cruz Xitla', 20);
INSERT INTO municipio VALUES (264 , 'San Miguel Chicahua', 20);
INSERT INTO municipio VALUES (385 , 'Santa Cruz Xoxocotlán', 20);
INSERT INTO municipio VALUES (143 , 'San Francisco Ixhuatán', 20);
INSERT INTO municipio VALUES (022 , 'Cosoltepec', 20);
INSERT INTO municipio VALUES (386 , 'Santa Cruz Zenzontepec', 20);
INSERT INTO municipio VALUES (023 , 'Cuilápam de Guerrero', 20);
INSERT INTO municipio VALUES (144 , 'San Francisco Jaltepetongo', 20);
INSERT INTO municipio VALUES (265 , 'San Miguel Chimalapa', 20);
INSERT INTO municipio VALUES (266 , 'San Miguel del Puerto', 20);
INSERT INTO municipio VALUES (145 , 'San Francisco Lachigoló', 20);
INSERT INTO municipio VALUES (024 , 'Cuyamecalco Villa de Zaragoza', 20);
INSERT INTO municipio VALUES (267 , 'San Miguel del Río', 20);
INSERT INTO municipio VALUES (146 , 'San Francisco Logueche', 20);
INSERT INTO municipio VALUES (025 , 'Chahuites', 20);
INSERT INTO municipio VALUES (389 , 'Santa Inés Yatzeche', 20);
INSERT INTO municipio VALUES (026 , 'Chalcatongo de Hidalgo', 20);
INSERT INTO municipio VALUES (027 , 'Chiquihuitlán de Benito Juárez', 20);
INSERT INTO municipio VALUES (148 , 'San Francisco Ozolotepec', 20);
INSERT INTO municipio VALUES (269 , 'San Miguel el Grande', 20);
INSERT INTO municipio VALUES (028 , 'Heroica Ciudad de Ejutla de Crespo', 20);
INSERT INTO municipio VALUES (029 , 'Eloxochitlán de Flores Magón', 20);
INSERT INTO municipio VALUES (390 , 'Santa Lucía del Camino', 20);
INSERT INTO municipio VALUES (270 , 'San Miguel Huautla', 20);
INSERT INTO municipio VALUES (391 , 'Santa Lucía Miahuatlán', 20);
INSERT INTO municipio VALUES (271 , 'San Miguel Mixtepec', 20);
INSERT INTO municipio VALUES (392 , 'Santa Lucía Monteverde', 20);
INSERT INTO municipio VALUES (150 , 'San Francisco Telixtlahuaca', 20);
INSERT INTO municipio VALUES (393 , 'Santa Lucía Ocotlán', 20);
INSERT INTO municipio VALUES (030 , 'El Espinal', 20);
INSERT INTO municipio VALUES (272 , 'San Miguel Panixtlahuaca', 20);
INSERT INTO municipio VALUES (273 , 'San Miguel Peras', 20);
INSERT INTO municipio VALUES (152 , 'San Francisco Tlapancingo', 20);
INSERT INTO municipio VALUES (031 , 'Tamazulápam del Espíritu Santo', 20);
INSERT INTO municipio VALUES (394 , 'Santa María Alotepec', 20);
INSERT INTO municipio VALUES (153 , 'San Gabriel Mixtepec', 20);
INSERT INTO municipio VALUES (274 , 'San Miguel Piedras', 20);
INSERT INTO municipio VALUES (395 , 'Santa María Apazco', 20);
INSERT INTO municipio VALUES (396 , 'Santa María la Asunción', 20);
INSERT INTO municipio VALUES (154 , 'San Ildefonso Amatlán', 20);
INSERT INTO municipio VALUES (275 , 'San Miguel Quetzaltepec', 20);
INSERT INTO municipio VALUES (397 , 'Heroica Ciudad de Tlaxiaco', 20);
INSERT INTO municipio VALUES (276 , 'San Miguel Santa Flor', 20);
INSERT INTO municipio VALUES (277 , 'Villa Sola de Vega', 20);
INSERT INTO municipio VALUES (035 , 'Guelatao de Juárez', 20);
INSERT INTO municipio VALUES (156 , 'San Ildefonso Villa Alta', 20);
INSERT INTO municipio VALUES (278 , 'San Miguel Soyaltepec', 20);
INSERT INTO municipio VALUES (399 , 'Santa María Atzompa', 20);
INSERT INTO municipio VALUES (036 , 'Guevea de Humboldt', 20);
INSERT INTO municipio VALUES (279 , 'San Miguel Suchixtepec', 20);
INSERT INTO municipio VALUES (158 , 'San Jacinto Tlacotepec', 20);
INSERT INTO municipio VALUES (037 , 'Mesones Hidalgo', 20);
INSERT INTO municipio VALUES (038 , 'Villa Hidalgo', 20);
INSERT INTO municipio VALUES (159 , 'San Jerónimo Coatlán', 20);
INSERT INTO municipio VALUES (039 , 'Heroica Ciudad de Huajuapan de León', 20);
INSERT INTO municipio VALUES (280 , 'Villa Talea de Castro', 20);
INSERT INTO municipio VALUES (160 , 'San Jerónimo Silacayoapilla', 20);
INSERT INTO municipio VALUES (040 , 'Huautepec', 20);
INSERT INTO municipio VALUES (282 , 'San Miguel Tenango', 20);
INSERT INTO municipio VALUES (041 , 'Huautla de Jiménez', 20);
INSERT INTO municipio VALUES (162 , 'San Jerónimo Taviche', 20);
INSERT INTO municipio VALUES (163 , 'San Jerónimo Tecóatl', 20);
INSERT INTO municipio VALUES (042 , 'Ixtlán de Juárez', 20);
INSERT INTO municipio VALUES (284 , 'San Miguel Tilquiápam', 20);
INSERT INTO municipio VALUES (043 , 'Heroica Ciudad de Juchitán de Zaragoza', 20);
INSERT INTO municipio VALUES (285 , 'San Miguel Tlacamama', 20);
INSERT INTO municipio VALUES (164 , 'San Jorge Nuchita', 20);
INSERT INTO municipio VALUES (044 , 'Loma Bonita', 20);
INSERT INTO municipio VALUES (286 , 'San Miguel Tlacotepec', 20);
INSERT INTO municipio VALUES (166 , 'San José Chiltepec', 20);
INSERT INTO municipio VALUES (287 , 'San Miguel Tulancingo', 20);
INSERT INTO municipio VALUES (288 , 'San Miguel Yotao', 20);
INSERT INTO municipio VALUES (169 , 'San José Independencia', 20);
INSERT INTO municipio VALUES (048 , 'Magdalena Mixtepec', 20);
INSERT INTO municipio VALUES (049 , 'Magdalena Ocotlán', 20);
INSERT INTO municipio VALUES (291 , 'San Pablo Coatlán', 20);
INSERT INTO municipio VALUES (170 , 'San José Lachiguiri', 20);
INSERT INTO municipio VALUES (171 , 'San José Tenango', 20);
INSERT INTO municipio VALUES (292 , 'San Pablo Cuatro Venados', 20);
INSERT INTO municipio VALUES (050 , 'Magdalena Peñasco', 20);
INSERT INTO municipio VALUES (293 , 'San Pablo Etla', 20);
INSERT INTO municipio VALUES (051 , 'Magdalena Teitipac', 20);
INSERT INTO municipio VALUES (173 , 'San Juan Atepec', 20);
INSERT INTO municipio VALUES (294 , 'San Pablo Huitzo', 20);
INSERT INTO municipio VALUES (052 , 'Magdalena Tequisistlán', 20);
INSERT INTO municipio VALUES (295 , 'San Pablo Huixtepec', 20);
INSERT INTO municipio VALUES (053 , 'Magdalena Tlacotepec', 20);
INSERT INTO municipio VALUES (175 , 'San Juan Bautista Atatlahuca', 20);
INSERT INTO municipio VALUES (296 , 'San Pablo Macuiltianguis', 20);
INSERT INTO municipio VALUES (176 , 'San Juan Bautista Coixtlahuaca', 20);
INSERT INTO municipio VALUES (297 , 'San Pablo Tijaltepec', 20);
INSERT INTO municipio VALUES (298 , 'San Pablo Villa de Mitla', 20);
INSERT INTO municipio VALUES (177 , 'San Juan Bautista Cuicatlán', 20);
INSERT INTO municipio VALUES (299 , 'San Pablo Yaganiza', 20);
INSERT INTO municipio VALUES (057 , 'Matías Romero Avendaño', 20);
INSERT INTO municipio VALUES (058 , 'Mazatlán Villa de Flores', 20);
INSERT INTO municipio VALUES (059 , 'Miahuatlán de Porfirio Díaz', 20);
INSERT INTO municipio VALUES (060 , 'Mixistlán de la Reforma', 20);
INSERT INTO municipio VALUES (182 , 'San Juan Bautista Tlacoatzintepec', 20);
INSERT INTO municipio VALUES (062 , 'Natividad', 20);
INSERT INTO municipio VALUES (183 , 'San Juan Bautista Tlachichilco', 20);
INSERT INTO municipio VALUES (184 , 'San Juan Bautista Tuxtepec', 20);
INSERT INTO municipio VALUES (064 , 'Nejapa de Madero', 20);
INSERT INTO municipio VALUES (185 , 'San Juan Cacahuatepec', 20);
INSERT INTO municipio VALUES (065 , 'Ixpantepec Nieves', 20);
INSERT INTO municipio VALUES (187 , 'San Juan Coatzóspam', 20);
INSERT INTO municipio VALUES (067 , 'Oaxaca de Juárez', 20);
INSERT INTO municipio VALUES (188 , 'San Juan Colorado', 20);
INSERT INTO municipio VALUES (189 , 'San Juan Comaltepec', 20);
INSERT INTO municipio VALUES (068 , 'Ocotlán de Morelos', 20);
INSERT INTO municipio VALUES (190 , 'San Juan Cotzocón', 20);
INSERT INTO municipio VALUES (191 , 'San Juan Chicomezúchil', 20);
INSERT INTO municipio VALUES (070 , 'Pinotepa de Don Luis', 20);
INSERT INTO municipio VALUES (071 , 'Pluma Hidalgo', 20);
INSERT INTO municipio VALUES (072 , 'San José del Progreso', 20);
INSERT INTO municipio VALUES (194 , 'San Juan del Río', 20);
INSERT INTO municipio VALUES (073 , 'Putla Villa de Guerrero', 20);
INSERT INTO municipio VALUES (074 , 'Santa Catarina Quioquitani', 20);
INSERT INTO municipio VALUES (195 , 'San Juan Diuxi', 20);
INSERT INTO municipio VALUES (196 , 'San Juan Evangelista Analco', 20);
INSERT INTO municipio VALUES (075 , 'Reforma de Pineda', 20);
INSERT INTO municipio VALUES (198 , 'San Juan Guichicovi', 20);
INSERT INTO municipio VALUES (199 , 'San Juan Ihualtepec', 20);
INSERT INTO municipio VALUES (079 , 'Salina Cruz', 20);
INSERT INTO municipio VALUES (081 , 'San Agustín Atenango', 20);
INSERT INTO municipio VALUES (082 , 'San Agustín Chayuco', 20);
INSERT INTO municipio VALUES (084 , 'San Agustín Etla', 20);
INSERT INTO municipio VALUES (085 , 'San Agustín Loxicha', 20);
INSERT INTO municipio VALUES (086 , 'San Agustín Tlacotepec', 20);
INSERT INTO municipio VALUES (090 , 'San Andrés Huaxpaltepec', 20);
INSERT INTO municipio VALUES (091 , 'San Andrés Huayápam', 20);
INSERT INTO municipio VALUES (092 , 'San Andrés Ixtlahuaca', 20);
INSERT INTO municipio VALUES (094 , 'San Andrés Nuxiño', 20);
INSERT INTO municipio VALUES (095 , 'San Andrés Paxtlán', 20);
INSERT INTO municipio VALUES (097 , 'San Andrés Solaga', 20);
INSERT INTO municipio VALUES (098 , 'San Andrés Teotilálpam', 20);